server:
  port: 9003
spring:
  application:
    name: dispatcher-service
  cloud:
    function:
      definition: pack|label
    stream:
      bindings:
        packlabel-in-0:
          destination: order-accepted #exchange name in rabbitmq
          group: ${spring.application.name} # queue name for the input exchange "destination.group"
        packlabel-out-0:
          destination: order-dispatched #exchange name in rabbitmq
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 5s